name: Docker CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # 基础语法检查 - 轻量级
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flask flask-cors pandas openpyxl pypinyin
    
    - name: Lint with flake8
      run: |
        # 忽略长行和一些Flask特定的问题
        flake8 . --count --max-line-length=120 --statistics --exclude=__pycache__ --ignore=E501,W503
    
    - name: Check Python syntax
      run: |
        python -m py_compile excel_web.py excel_processor.py config.py file_cleaner.py

  # Docker构建测试 - 确保Dockerfile正常工作
  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Test Docker build
      run: |
        docker build -t test-image .
        
    - name: Test container startup
      run: |
        # 启动容器并测试健康检查
        docker run -d --name test-container -p 4009:4009 test-image
        sleep 15
        # 简单的健康检查
        curl -f http://localhost:4009/health || exit 1
        docker stop test-container
